### PR TITLE
White paper 2022

### PR DESCRIPTION
**Pull request by xfq**
[Preview](https://raw.githack.com/w3c/miniapp/white-paper-2022/white-paper/index.html#abstract) [Diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fminiapp%2Fwhite-paper%2F&doc2=https%3A%2F%2Fraw.githack.com%2Fw3c%2Fminiapp%2Fwhite-paper-2022%2Fwhite-paper%2Findex.html)

### CODE REVIEW

**Comment by xfq** [comment]
@espinr Do you have the source file for [miniapp_pwa.png](https://github.com/w3c/miniapp/blob/c0084e4ee7b3268ab1e83949ea2a3604854be172/white-paper/images/miniapp_pwa.png)?

**Comment by espinr** [comment]
@xfq I've updated the PNG and included the SVG (this is now linked from the index.html).

**Comment by espinr** [comment]
:( I totally messed up the branches and I included the changes in the PWA-MiniApp comparison table. I reverted the changes in that file. I'm sorry for the mess. I think it's solved. Only the images added.

**Comment by xfq** [comment]
Merging per https://www.w3.org/2022/04/28-MiniApp-minutes.html#t05

**Pull request merged**
